<?xml version="1.0"?>
<!--
  LPLidar Sensor
 -->
<robot name="sensor_lplidar" xmlns:xacro="http://ros.org/wiki/xacro">
 
  <!-- Xacro properties  -->
  <xacro:property name="LIDAR_BASE_HEIGHT" value="0.022" />
  <xacro:property name="LIDAR_SPINNER_HEIGHT" value="0.012" />
  <xacro:property name="LIDAR_RADIUS" value="0.038" />
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <material name="Green">
    <color rgba="0.0 1.0 0.0 1"/>
  </material>
  <material name="Red">
    <color rgba="1.0 0.0 0.0 1"/>
  </material>

  <xacro:macro name="sensor_lplidar" params="parent *origin">
    <joint name="lidar_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="lidar_base_link" />
    </joint>

    <link name="lidar_base_link">
      <visual>
        <geometry>
          <cylinder length="${LIDAR_BASE_HEIGHT}" radius="${LIDAR_RADIUS}"/>
        </geometry>
        <material name="Green" />
        <origin xyz="0.0 0.0 ${LIDAR_BASE_HEIGHT/2.0}" rpy="0.0 0.0 0.0"/>
      </visual>
      <inertial>
        <mass value="0.000001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>
    </link>

    <joint name="lidar_top_joint" type="fixed">
      <origin xyz="0.0 0.0 ${LIDAR_BASE_HEIGHT+(LIDAR_SPINNER_HEIGHT/2.0)}" rpy="0.0 0.0 ${M_PI}" /> 
      <parent link="lidar_base_link" />
      <child link="lidar_link" />
    </joint>

    <link name="lidar_link">
      <visual>
        <geometry>
          <cylinder length="${LIDAR_SPINNER_HEIGHT}" radius="${LIDAR_RADIUS}"/>
        </geometry>
        <material name="Red" />
      </visual>
      <inertial>
        <mass value="0.000001" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001" />
      </inertial>
    </link>

  </xacro:macro>
</robot>


